### ISSUE TITLE
Modifier le front GN2 pour ne pas afficher les JDD inactif en edition

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-migration#4]

**Comment by camillemonchicourt** [comment]
Dépendant de https://github.com/PnX-SI/GeoNature/issues/694

**Comment by TheoLechemia** [comment]
Fait: https://github.com/PnX-SI/GeoNature/commit/8079f769ef10d00a9c52408df4198a4a3d0a5bfe
